<?php

namespace app\models;

use Yii;
use app\models\User;

/**
 * This is the model class for table "anonymus_push".
 *
 * @property string $push_token
 *
 * @property Attribute $attr
 * @property AttributeValue[] $attributeValues
 */
class AnonymusPush extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'anonymus_push';
    }

    public function rules()
    {
        return [
            [['push_token'], 'string', 'length' => [10, 300]],
//            [['push_token'], 'unique'],
        ];
    }

    public function beforeSave($insert)
    {
        if($this->validate()){
            return parent::beforeSave($insert); // TODO: Change the autogenerated stub
        }else{
            return;
        }

    }


    public static function getPushTokens() {
        return self::find()->select('push_token')->distinct()->column();
    }

    public static function primaryKey()
    {
        return [
            'push_token'
        ];
    }
}
